### PR TITLE
Dockerize the project and add a RESTful service to process images

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This pull request extends the current code base to add Docker compliance and a RESTful service that can be used to process images without having to execute Python locally.

All the dependencies are covered with the Docker file that has been added. It requires only one command line to get an image to be processed.

I hope you like this addition to the project.

Cheers,
Wilder

### CODE REVIEW

**Comment by oarriaga** [comment]
@wilderrodrigues thank you very much for your PR. I am however, writing version 2  of my code (in the v2 branch) which re-structures most my code and also adds different video/image tests. This current PR has merge conflicts with my v2 branch. I will hopefully merge my branch next week, and then we can see how to restructure your PR, specifically the Docker file to include it into the project. Thank you very much.

**Comment by wilderrodrigues** [comment]
Hi @oarriaga,

Okay, no problem. I will be on holidays from tomorrow, but once I'm back I will have a look at the conflicts and get them fixed so we can - hopefully - get it merged. :)

Thanks a lot for the great project.

Cheers, Wilder

**Comment by Zumbalamambo** [comment]
how do i download this pull request?

**Comment by wilderrodrigues** [comment]
@Zumbalamambo @oarriaga 

Sorry for the delay, I was on holidays.

The current master branch on my fork has the changes: https://github.com/ekholabs/face_classification

I will fix the conflicts and get the PR updated.

Cheers, Wilder

**Comment by Zumbalamambo** [comment]
Okay thank you. Looking forward for the same. the accuracy is too low in current model. especially for asian faces. Refer [this ](https://github.com/oarriaga/face_classification/issues/24) issue. I have tried fixing it but still the accuracy is too low.

**Comment by oarriaga** [comment]
@Zumbalamambo could you please estimate what do you mean by "the accuracy is to low"? I mean could you give a script with a dataset that tries to classify different faces and indeed achieves a low accuracy?
Thank you.

**Comment by Zumbalamambo** [comment]
I tried the same example as in the code that you have pushed to recognize asian faces and its accuracy is too low. It is less than 70% for asian faces when I try to detect realtime.

**Comment by wilderrodrigues** [comment]
Hi guys,

Got lots of conflicts when tried to rebase. I ended up adding the files that were changed manually and got the whole thing to work again.

I will push my changes and try to rebase again, so i get the commits from @oarriaga in place: he deserves the credits. :)

**Comment by wilderrodrigues** [comment]
Hi @oarriaga,

The PR is now fixed and can be merged if you agree.

Cheers, Wilder

**Comment by moriarty** [comment]
@oarriaga I tested the master branch of @wilderrodrigues and it worked 👍 with ```./images/test_image.jgp```

When it didn't work, it sometimes filled the output image with
```
{
  "error": "We cannot process the file sent in the request."
}
```
which is reasonable.

If it failed to detect my face, it returned an image that looked the same but the binary was different, but passing it the same image again, and comparing the first returned image and the second, the binary was the same- so it's consistent.

It didn't like to detect my face when I had my glasses on, but when I took them off it classified me as a sad man 👎 

You should merge this

**Comment by wilderrodrigues** [comment]
Thanks, @moriarty ! :)

**Pull request merged**
